// This file is generated by scripts/i18n-keys.js
// Do not edit this file directly.
/* eslint-disable */
export const I18N_KEYS = {
  "home": "home",
  "hello": "hello",
  "common": {
    "search": "common.search",
    "noData": "common.noData",
    "actions": "common.actions",
    "view": "common.view",
    "detail": "common.detail",
    "edit": "common.edit",
    "delete": "common.delete",
    "add": "common.add",
    "save": "common.save",
    "cancel": "common.cancel",
    "confirm": "common.confirm",
    "jumpTo": "common.jumpTo",
    "all": "common.all",
    "createdTime": "common.createdTime",
    "id": "common.id",
    "icon": "common.icon",
    "title": "common.title",
    "close": "common.close",
    "confirmDelete": "common.confirmDelete",
    "deleteSuccess": "common.deleteSuccess",
    "deleteFail": "common.deleteFail",
    "addSuccess": "common.addSuccess",
    "addFail": "common.addFail",
    "editSuccess": "common.editSuccess",
    "editFail": "common.editFail",
    "saveSuccess": "common.saveSuccess",
    "saveFail": "common.saveFail",
    "formInvalid": "common.formInvalid",
    "updatedTime": "common.updatedTime",
    "pageNotFound": "common.pageNotFound"
  },
  "login": {
    "username": "login.username",
    "email": "login.email",
    "password": "login.password",
    "login": "login.login",
    "logout": "login.logout",
    "usernamePlaceholder": "login.usernamePlaceholder",
    "emailPlaceholder": "login.emailPlaceholder",
    "passwordPlaceholder": "login.passwordPlaceholder"
  },
  "language": "language",
  "validation": {
    "required": "validation.required",
    "minlength": "validation.minlength",
    "maxlength": "validation.maxlength",
    "email": "validation.email"
  },
  "menu": {
    "user": "menu.user",
    "userDetail": "menu.userDetail",
    "changePassword": "menu.changePassword",
    "blog": "menu.blog",
    "blogList": "menu.blogList",
    "blogDetail": "menu.blogDetail",
    "blogAdd": "menu.blogAdd",
    "blogEdit": "menu.blogEdit",
    "blogCategory": "menu.blogCategory"
  }
};
