@AdminService_HostAddress = https://localhost:17001/api

POST {{AdminService_HostAddress}}/user
Accept: application/json
Content-Type: application/json

{
  "userName": "admin@default.com",
  "password": "Perigon.2026",
  "nickName": "Admin User"
}

### 

// @name auth
POST {{AdminService_HostAddress}}/user/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@default.com",
  "password": "Perigon.2026"
}

###

PATCH {{AdminService_HostAddress}}/user/019bb5e6-450e-7bfc-a1c5-3006f1d74d5b
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth.response.body.$.accessToken}}

{
  "password": "Perigon.2026"
}

###

GET {{AdminService_HostAddress}}/user/detail
Accept: application/json
Authorization: Bearer {{auth.response.body.$.accessToken}}

###

POST {{AdminService_HostAddress}}/BlogCategory
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth.response.body.$.accessToken}}

{
  "name": "Technology",
  "description": "All about the latest in tech."
}